### ISSUE TITLE
Are Alphis test-ip4.alfis.name and test-ip6.alfis.name servers offline/down?

### ISSUE THREAD

**Issue by alexis-evelyn** [Revertron/Alfis#101]
Currently I'm unable to get any blocks past 398 (and am not sure how many there even is left) and I tried to get it on two different computers on two different networks, both via yggdrasil and via regular internet. Both of these scripts reached 398 blocks independently of each other and will not get past that number. The GUI on the Mac still says connecting and when clicking it and then confirm on the stop mining button (hadn't even started mining, I just start up the program), it does nothing. I have to exit it either via the Mac Cmd+Q hotkey or the Window's X button.

I'm not sure if this is a bug in the current client or if something's up with the server end, but I'm not able to even tell if I finished syncing the blockchain or not, much less how much is left. It's been stuck on 398 for over an hour now.

![Screen Shot 2021-05-03 at 3 57 32 PM](https://user-images.githubusercontent.com/6305346/116926447-5d5d5880-ac28-11eb-809c-27c58ed5df4f.png)

![Screen Shot 2021-05-03 at 3 57 18 PM](https://user-images.githubusercontent.com/6305346/116926450-5df5ef00-ac28-11eb-98cc-1c7a710cbbd2.png)

**Comment by Revertron** [comment]
We are in a process of restarting the chain.
I will release a 0.5.0 version in one or two days.
It will have 10 predetermined zones to prevent any abuse, and some new features.

The dialog about stopping mining is a known UI bug, I just have no time to address :)
All other behavior is normal.
