### ISSUE TITLE
Unable to set contact information

### ISSUE THREAD

**Issue by xaozai** [Revertron/Alfis#107]
I tried to provide a link to the contact information, and got this:

![IMG_6001](https://user-images.githubusercontent.com/8542452/117196891-c5aa6680-adef-11eb-93d3-111d0bea24d6.jpg)

Without specifying the contact information, mining started normally

**Comment by Revertron** [comment]
Thanks, I will check it.

**Comment by xaozai** [comment]
In the latest version, this works fine.
