### ISSUE TITLE
Feature request: Info about the mining process

### ISSUE THREAD

**Issue by xaozai** [Revertron/Alfis#11]
Is it possible to display somewhere in this window how long the mining process has already been going on and the estimated / approximate time of the end of mining? And also, display during mining, which records will be added to the block.

![request](https://user-images.githubusercontent.com/8542452/113291487-c6853f80-92fb-11eb-971f-3ff37174c439.png)

And the same thing, when mining the key.

**Comment by Revertron** [comment]
There is no way to make any estimates.
But everything else will appear in `Events` tab. When I'll get some time to work on it.

**Comment by Vort** [comment]
At least, it is possible to write in documentation if it takes minutes, hours or days with average PC.

**Comment by Revertron** [comment]
@Vort, it takes from 30 seconds to 40 minutes on my Ryzen 7 3700X. Is it worth of mentioning?

**Comment by Vort** [comment]
It is better than nothing. Thanks.
Theoretically, it should be possible to obtain result like "90% of mining chance in xx minutes on Ryzen 7 3700X".

**Comment by Vort** [comment]
I have found that it is possible to display keys mining speed with `-d` option.
For single core of my i5-4690 result is:
`09:08:39 [DEBUG] alfis::keys: Mining speed 14 H/s`
Which means that for 50% mining chance I need to spend 5 days _(if my calculations are correct)_.

Either Windows build use no optimizations or this sotware targets only users with modern hardware.
By the way, I think that mining speed should also go to UI somewhere, not only to console with additinal flags.

**Comment by alexis-evelyn** [comment]
Hmmmmm. Currently I have 44 blocks and my hash rate is ranging from 2 H/s to 12 H/s. Like, I just want to have a domain for yggdrasil. I don't exactly have a fancy gpu. Not that I can tell if Alfis is even using the internal GPU at all. So, I'm currently trying to work out how long it would take to mine, especially since Alfis is leaning more towards 2 H/s.

**Comment by Vort** [comment]
@alexis-evelyn looks like several months :(
@Revertron what is hashrate for your CPU (both single core and all cores)?

**Comment by RedGlow** [comment]
I noticed the author has closed this ticket, although it seems like @Vort suggested some interesting way to express mining speed through probabilities. Is this still on radar?

As an extra info: how should the speed be interpreted? I don't know what the unit "H/s" indicates ("something" per second, I guess, but what?)

**Comment by Vort** [comment]
> I don't know what the unit "H/s" indicates ("something" per second, I guess, but what?)

Hashes per second. Keypairs are generated and for each public key hash is calculated, until sequence with 23 zero bits is found [(source [ru])](https://github.com/Revertron/Alfis/blob/master/docs/about_ru.md).

**Comment by 174n** [comment]
> it takes from 30 seconds to 40 minutes on my Ryzen 7 3700X

I have a Ryzen 9 3900X (a better one I think) and it's already taking more than an hour. How did you get this numbers?
