### ISSUE TITLE
Would you believe that my ISP, Comcast, is blocking the connection?

### ISSUE THREAD

**Issue by alexis-evelyn** [Revertron/Alfis#110]

**Comment by alexis-evelyn** [comment]
So, I ended up renting a VM that allows crypto mining which can let me generate the keys I need and apparently the connection just decided nope, no matter if I use VPN, hotspot, or anything (when testing locally to eliminate reasons why the VM can't connect).

![Screen Shot 2021-05-12 at 2 21 43 PM](https://user-images.githubusercontent.com/6305346/118025058-67204380-b32d-11eb-9be1-d36d11006759.png)
![Screen Shot 2021-05-12 at 2 21 00 PM](https://user-images.githubusercontent.com/6305346/118025071-68ea0700-b32d-11eb-8819-e402792852ec.png)

**Comment by Revertron** [comment]
I plan to publish 0.6.0 release tomorrow.
It will use strong ECDH encryption for P2P-connections.

**Comment by Revertron** [comment]
@alexis-evelyn, did you try version 0.6.0? Does Comcast block its P2P connections?
