### ISSUE TITLE
[Question] How often will the domains be reset, if ever?

### ISSUE THREAD

**Issue by alexis-evelyn** [Revertron/Alfis#111]
Unless something's wrong with my connection, I received the Syncing Finished message after downloading 44 blocks (whereas when I made my first issue, there were at least 398 blocks).

I presume that the whole chain was reset due to implementing predefined TLDs to prevent abuse (https://github.com/Revertron/Alfis/issues/101#issuecomment-831521519). So, I wanted to ask if there was a reset and how often the chain my reset. That way I know when to remine the domains I have already mined (haven't mined any yet, but in the hypothetical, I will have already mined at least a couple).

This question exists in the form of an issue as I cannot find any documentation, not even a wiki page on Alfis. Thanks!

**Comment by Revertron** [comment]
We've just restarted new chain (with some days of secret premining of PoS), hopefully it will be as stable as we need.
Just grab the [current release](https://github.com/Revertron/Alfis/releases/tag/v0.5.3) and don't forget to change `origin` in config to `0000001D2A77D63477172678502E51DE7F346061FF7EB188A2445ECA3FC0780E`.
