### ISSUE TITLE
The color of the message " Mining unsuccessful, sorry."

### ISSUE THREAD

**Issue by xaozai** [Revertron/Alfis#113]
Could you make the color of this message pink?

![Снимок экрана_2021-05-11_22-41-14](https://user-images.githubusercontent.com/8542452/117875212-917ced00-b2aa-11eb-88b0-778769d7220a.png)

The color of the message of successful and unsuccessful mining is the same - this is wrong.

**Comment by Revertron** [comment]
Fixed in 0.5.9.
