### ISSUE TITLE
Add .key zone

### ISSUE THREAD

**Issue by eatb33ts** [Revertron/Alfis#116]
A `.key` zone would be useful for DNS based verification of information that users would like associated with a public key.

For example:
- pubkey to domain name mapping (like PTR records but for pubkeys).
- routing/IP address
- contact information
- configuration information

A side benefit is that this would also mitigate address collisions in yggdrasil as described [here.](https://github.com/yggdrasil-network/yggdrasil-go/issues/779)

Some questions:
Should name registration be restricted to only the key that mined that block such that only `alfis_pubkey.key` can be registered?
Or maybe restricted blocks should be a different zone such as `.alfis`?
Could existing ed25519 (ssh?) keys be used to sign these blocks?

Would lowering the minimum difficulty be useful? We don't want to spam the blockchain but we also don't want to have someone else steal a public key before a user can mine it, or for the user to wait too long before they can use it.

**Comment by Revertron** [comment]
The list of domain zones is encoded in the first block of the chain, the `origin` or `genesis`. We can't add or remove anything.

I didn't understand your questions, sorry. What do you want to achieve?

**Comment by eatb33ts** [comment]
If domains can't be added the questions are moot. 

The questions were mainly around protecting the name from hijacking by another person that has obtained the public key.
Now that I have slept and thought about it, the restriction seems like the right way to go, if this is able to be implemented in the future.

For example, `.key` would be a special zone where names can be mined by any compatible key you might have on your computer such as ssh. The block will only be considered valid if the name `pubkey-abcdef.key` matches the `pubkey-abcdef` of the signer. This would prevent name hijacking since pubkeys are supposed to be public.

Hopefully that makes sense.

**Comment by Revertron** [comment]
I am planing to make possible to store public keys in blockchain, but not in the form of domains. It would be some other transaction type.
