### ISSUE TITLE
Very unstable connection to nodes

### ISSUE THREAD

**Issue by xaozai** [Revertron/Alfis#12]
Node connections are very unstable. They are interrupted and created every 2-3 seconds.
At the same time, I use the network, visit sites, ping nodes without any problems.
Connections are interrupted even between nodes inside my local network (IPv4).

![scr](https://user-images.githubusercontent.com/8542452/113397166-49160980-93a5-11eb-9547-170db36cec1e.png)

![scr2](https://user-images.githubusercontent.com/8542452/113397800-4b2c9800-93a6-11eb-8582-eebbcf23c1b3.png)

![scr3](https://user-images.githubusercontent.com/8542452/113398879-f68a1c80-93a7-11eb-92af-d4fcc980a534.png)

**Comment by Revertron** [comment]
I think I've managed to stabilize the network a lot in https://github.com/Revertron/Alfis/releases/tag/v0.3.11

**Comment by xaozai** [comment]
Unfortunately, I'm still seeing the same thing with 0.3.11.

![02-04-2021 23-18-49](https://user-images.githubusercontent.com/8542452/113451223-384baf00-940a-11eb-9957-070530891bc7.png)

**Comment by Revertron** [comment]
Be aware, that "created connection" doesn't mean that connection has been made. It just tries to connect. And shutdown is normal if that node didn't respond.

**Comment by xaozai** [comment]
But it goes on forever. Why is it trying to connect to non-responding / non-existent nodes then?

**Comment by Revertron** [comment]
That is another problem, I will fix it soon :)

**Comment by Revertron** [comment]
@xaozai, did you try version v0.3.13? It must be a way better experience.

**Comment by xaozai** [comment]
Looks like it's getting better now.

Although, in the log with a certain period, such messages appear:

![1](https://user-images.githubusercontent.com/8542452/113545523-00ec2680-95f3-11eb-8661-262dc9d27e25.png)

![2](https://user-images.githubusercontent.com/8542452/113545542-08abcb00-95f3-11eb-8ccd-4628c76066bf.png)

![3](https://user-images.githubusercontent.com/8542452/113545552-0cd7e880-95f3-11eb-87d7-fae3bc642c56.png)

**Comment by Revertron** [comment]
This is normal, don't alarm yourself :)
I'm closing the issue for now, if something new arises feel free to reopen.

**Comment by bitcoren** [comment]
Can't connect.
Alfis 0.4.23
Windows Server 2019
Windows 10 Pro
![изображение](https://user-images.githubusercontent.com/38252897/115796471-708c4f00-a404-11eb-985b-19dd50426d18.png)
