### ISSUE TITLE
Why mineing is too slow?

### ISSUE THREAD

**Issue by rdp-studio** [Revertron/Alfis#166]

**Comment by Revertron** [comment]
To prevent [Cybersquatting](https://en.wikipedia.org/wiki/Cybersquatting).

**Comment by PoneyClairDeLune** [comment]
Mined for literally 12 hours with no new key at all...

**Comment by Revertron** [comment]
> 
> 
> Mined for literally 12 hours with no new key at all... Wanted to try ALFIS, and stuck on the creation of keys

Then the anti-squatting solution works as it should.

**Comment by PoneyClairDeLune** [comment]
> > Mined for literally 12 hours with no new key at all... Wanted to try ALFIS, and stuck on the creation of keys
> 
> Then the anti-squatting solution works as it should.

A little too well, I'd say...
I'll place my DNS resolutions on clearnet instead. I have literally no key to register anything on ALFIS.
