### ISSUE TITLE
How long does it take to mine a key? 

### ISSUE THREAD

**Issue by marek22k** [Revertron/Alfis#197]
Hello,

For more than 12 hours I have tried to mine a key with 8 CPU cores (11th Gen Intel® Core ™ i7-1165G7 @ 2.80GHz × 8), but without success.
How long does it take on average to mine a key?

**Comment by Revertron** [comment]
It depends on your "luck" only (or a source of randomness in your OS). Sometimes 5 minutes, sometimes 12-24 hours.
