### ISSUE TITLE
Panic on system wake up

### ISSUE THREAD

**Issue by averyanalex** [Revertron/Alfis#218]
After the system wakes up from sleep, Alfis sometimes crashes. Maybe it can occur on internet connection loss too. Log:
thread '<unnamed>' panicked at 'Error polling sockets: Os { code: 4, kind: Interrupted, message: "Прерван системный вызов" }', src/p2p/network.rs:91:50
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
Link to code: https://github.com/Revertron/Alfis/blob/c111da62506610f1de327a715abf9c9ca284ee6a/src/p2p/network.rs#L91
Version: v0.6.10

**Comment by Revertron** [comment]
@averyanalex, could you please test current `master` version?
