### ISSUE TITLE
Security: disclosing real IP addresses of users 

### ISSUE THREAD

**Issue by xaozai** [Revertron/Alfis#26]
Some users register in the zone .ygg domains with IP addresses from the internet (See block 26.).
Other users who will visit the site using this domain name will disclose their real IP addresses to the owner of the resource.
Because It is not obvious that the .ygg zone can have addresses from the Internet.
I think it is necessary for each zone to map a range of IP addresses for which a domain can be registered in this zone.
Or something similar.

**Comment by Revertron** [comment]
ALFIS is a Domain Name System. It just provides a way to create domains and keep them going. If you need it to be part-functional I cannot help you with that.
Just try to convince domain administrators not to use those zones with internet IPs.

**Comment by r4sas** [comment]
@Revertron maybe adding some config option to disable responding with `A` records?

**Comment by Revertron** [comment]
> 
> 
> @Revertron maybe adding some config option to disable responding with `A` records?

Thinking about it.

**Comment by Bogdan107** [comment]
> Thinking about it.

IP addresses from the internet has adresses in AAAA records too...
How about make custom filter for responding with any records?

For example (in /etc/yggdrasil.conf):
```
ResponseIPAllow: [
  200::/7
  300::/64
]
```

**Comment by Revertron** [comment]
The concept has changed since the topic was started.
Now all zones have a flag `Yggdrasil only`. You can not add records `A` and records `AAAA` with addresses not from Yggdrasil.
