### ISSUE TITLE
DNS server doesn't bind to all localhost interfaces.

### ISSUE THREAD

**Issue by zander** [Revertron/Alfis#332]
Using the latest release (0.8.3) I run alfis under systemd.

Calling `time drill flowee.ygg @localhost  AAAA` I notice I get a correct response very quickly, but once every 5 to 10 calls it just hangs for 15 seconds.

```
real    0m15,021s
user    0m0,003s
sys     0m0,003s
```

Even after nobody asked the server for half an hour, a call took 15 seconds. So there doesn't seem to be any shortage of workers (unless they don't die at all)

**Comment by Revertron** [comment]
Can you repeat that test now, when your blockchain is fully synced?

**Comment by zander** [comment]
My blockchain has been fully synched for all those tests.

I even mined my own domain, which is what the test tried to query. The result was correct 100% of the time, the hanging is just a problem.

**Comment by Revertron** [comment]
I can't reproduce it here. On Windows and Linux :(

**Comment by zander** [comment]
I restarted the server with debug level output, which revealed nothing useful.

My observations;

* Debug messages like "connection 10 to IP has timed out" etc still continue to scroll by in the time the connection is waiting for answer.
* forwarded requests also block, just like alfis lookups do.
* its ALWAYS exactly 15 seconds extra.
* using 'ping' to do lookups seems to work just fine.
* Changing the number of threads to 100 had no effect.

Attached is are 2 strace logs, maybe that helps.

[strace-normal.log](https://github.com/Revertron/Alfis/files/10446230/strace-normal.log)
[strace-slow.log](https://github.com/Revertron/Alfis/files/10446231/strace-slow.log)

**Comment by zander** [comment]
Thats one explanation.

The socket connection and timeouts are a bit weird, though. It seems to connect 3 times to ::1 before trying to connect to 127.0.0.1

Looks like the problem is that your DNS server only binds to one localhost, not to the ipv6 localhost.

**Comment by zander** [comment]
To add the info you explained in private chat;

Alfis is currently unable to bind to more than one interface. So a dual-stack system like my own where the 'localhost' has two interfaces will mean that the user needs to address the server by IP address instead of name (localhost).
