### ISSUE TITLE
domain not working

### ISSUE THREAD

**Issue by blade10101** [Revertron/Alfis#359]
I have mined and created the domain hanssen.ygg but it dosen't get sent to the blockchain as its not resolvable

**Comment by Revertron** [comment]
You actually made a record `hanssen.hanssen.ygg`.
If you want to add some records to your "second level domain" (hanssen.ygg), you need to use `@` as record name.
And if you want every subdomain to redirect to `hanssen.ygg`, then you can use `*` as the record name.

**Comment by blade10101** [comment]
Thanks for the assistance

Use PGP! 7a98ff6d7cdd923fb4db944130055f19f2404155

Sent with Proton Mail secure email.
