### ISSUE TITLE
Feature request: PTR-records

### ISSUE THREAD

**Issue by xaozai** [Revertron/Alfis#36]
It would be nice if ALFIS could respond to reverse requests and return a PTR record.

**Comment by xaozai** [comment]
From Yggdrasil, of course.
That is, with this command would like to get the domain name of the server: `dig -x ipv6addr +short `

**Comment by Revertron** [comment]
Okay, generally, the owner of an IP is managing PTR-records. How could he/she propagate this information?

**Comment by xaozai** [comment]
We can introduce such a rule: if there is a PTR record, then for the domain in it, there must be a regular record. And when a PTR record is mined, we can compare the hash of the domain in it with the hash of the domain of the PTR record. Thus, PTR records can be distributed, like other records, in blocks.

**Comment by Revertron** [comment]
So, I can mine some domain i.e. `bad-guy-xaozai.ygg` with your IP in PTR record and your IP is doomed?

**Comment by xaozai** [comment]
Please see the message above. To mine a PTR record, you must have a regular record for the bad-guy-xaozai.ygg domain. 
If there is no regular record for this domain, the PTR record will not be added to the block.

In other cases, you can mine any domain names in conjunction with any IP addresses you want )

You mine `bad-guy`, and I'll mine `good-boy` )

Also, I can mine, `yo-rev-bruh.ygg` with IP address `300:b24b:: 69`. What's stopping me? )

**Comment by Revertron** [comment]
You contradict yourself :)

**Comment by xaozai** [comment]
In theory, there can be several PTR records... Although, usually, it is one...
In general, either that, or, I do not know how... )

**Comment by Revertron** [comment]
A single option is to create some sort of "agent" that will listen on some port, say 4245 UDP, and will answer requests with it's PTR record. The ALFIS could make such requests and relay the answer to the user.

**Comment by xaozai** [comment]
I assume that this port will be closed by a firewall for everyone...
However, it's better than nothing.

**Comment by Revertron** [comment]
Outgoing, where ALFIS is, or incoming on that IP?

**Comment by xaozai** [comment]
Port for incoming connections. Outgoing connections are rarely filtered by anyone...

**Comment by Revertron** [comment]
Then, if you really want PTR for your IP, you need to do something about it. Open the port, run some agent...

**Comment by xaozai** [comment]
PTR records are usually used to make sure that you are not being misled in a system, such as email, and others where having a domain name is critical to functioning. Thus, opening a port is not required on my server, but for example on a remote mail server that communicates with mine...

**Comment by Revertron** [comment]
Firstly, checking PTR-record on mail-servers to fight the spam is very old and rare function now.

But anyway, I think you are mistaken. If you send an e-mail to some server, and it uses ALFIS, it will check your record through it, and you need to have that daemon.
But if they send you an e-mail, and you want to check their PTR-record, they have to have that daemon running (and port open).

**Comment by xaozai** [comment]
OK, if you implement it this way, it will be fine )

**Comment by Bogdan107** [comment]
> It would be nice if ALFIS could respond to reverse requests and return a PTR record.

What problem will be solved by improving this feature?

I think, that sens of ALFIS-like systems in decentralizing of domain resolving system to each computer.
Normal way of usage of ALFIS database - to resolve local DNS queries. In normal way, all domain system information are placed in local database, not on remote DNS server.
So, If domain name registered in ALFIS database, then PTR record for those domain name (if it really needs to be registered in ALFIS system) MUST BE PLACED IN ALFIS DATABASE.

But!
If ALFIS register all domain information with all subdomains, then ALFIS database will be very big, and more than it necessary for comfort usage (as compromise between centralized and decentralized form, and size of database file).
If ALFIS system used in controlled environment - it is normal practice to register all info about domain and his subdomains in ALFIS database,
But if ALFIS used in global environment - then extended information for domain or info about his subdomains - is ballast, which exerts unnecessary stress to database size.
I think, that PTR record, of course, MUST be as optional feature in ALFIS database, but marked as BAD PRACTICE for global usage.

My proposal **for global usage**:
- use ALFIS database for hosting little domain info;
- use ALFIS database as start point to find NS server for find extended domain info (like PTR records);
- use owner DNS-server to resolve extended domain info (like PTR) or info about tens/hundreds subdomains (not an ALFIS database);
- use specialized domain resolver program (like dnsmasq/Unbound/Bind/PowerDNS/etc) for resolving domains;
- use ALFIS system **as domain management system**, not as DNS-server (see #71).

May be improve rules FOR GLOBAL USAGE:
- if domain has more than 3 records, then domain owner MUST use his own DNS-server for resolving his extended domain information;
- PTR record in ALFIS database - is BAD PRACTICE FRO GLOBAL USAGE (maybe improve harden requrements for generating extended domain records, like PTR or any other, than A or AAAA).

**Comment by Revertron** [comment]
@Bogdan107, nope :)
