### ISSUE TITLE
Endless "Connecting..."

### ISSUE THREAD

**Issue by nxshock** [Revertron/Alfis#44]
- Arch Linux
- Alfis 0.4.3
- webkit2gtk 2.32.0
- New config created by `alfis -g alfis.conf`
- Alfis started with `-v` switch

There is no messages about failed connections. Why do I see endless `Connecting...`?

![screenshot](https://user-images.githubusercontent.com/17479217/114901006-d0e02700-9e2d-11eb-8772-81e6c26114d4.png)

**Comment by Revertron** [comment]
I think there is some problem with the browser engine on Arch. Need more investigation.

**Comment by Revertron** [comment]
The problem is exactly like there: https://github.com/Boscop/web-view/issues/212
Added a workaround, it works flawlessly.
