### ISSUE TITLE
When loading the key, my domains are displayed incorrectly

### ISSUE THREAD

**Issue by xaozai** [Revertron/Alfis#48]
I have mained two domains , but in ALFIS they are displayed like this:

![Снимок экрана_2021-04-16_21-51-38](https://user-images.githubusercontent.com/8542452/115071334-ce99cd80-9efe-11eb-9d69-e7a8d1b7370a.png)

**Comment by Revertron** [comment]
This is a know issue, as stated in release notes.
You can remine that domain, it will appear normally.

Maybe I will find some time to make some workaround, don't know...

**Comment by xaozai** [comment]
Mining again? : (  I don't want to mine these two domains again.

**Comment by xaozai** [comment]
The problem is not solved :(

**Comment by Revertron** [comment]
Do you want me to throw away whole current blockchain and start over? This is the only chance besides remining.
