### ISSUE TITLE
Do we need mining when renewing or modifying domains?

### ISSUE THREAD

**Issue by xaozai** [Revertron/Alfis#52]
Here's what I thought: I've already mined the domains with my key. When I will renew these domains or modify something for some reason (for example, as [here](https://github.com/Revertron/Alfis/issues/48)) does it make sense to mine them with the initial difficulty?
After all, if I want to modify something with my key, can i just mine any block with any number of zeros at the beginning or end in the hash, and even with their absence?
Could you implement this? Please.

**Comment by Revertron** [comment]
The short answer is No.
The long one - if we allow people to mine blocks cheaply, they will abuse the system and mine thousands of blocks daily. Then, the main point "To invent small and easily manageable blockchain" will be unfeasible.

**Comment by blade10101** [comment]
I never did see how you were supposed to host a domain...

**Comment by Revertron** [comment]
> I never did see how you were supposed to host a domain...

There is no such thing as "hosting a domain" in blockchain-based DNS.
