### ISSUE TITLE
Question: How do I "transfer" a domain to another key?

### ISSUE THREAD

**Issue by xaozai** [Revertron/Alfis#72]
How do I "transfer" a domain to another key?
I don't want to transfer the domain to another person, I just want to separate the domains that have been mined with a single key.
Is it possible? And if it is not yet possible, is it planned in the future?

**Comment by Revertron** [comment]
Yes, it will be available in future. I just have to find the time to work this out.

**Comment by xaozai** [comment]
Implemented in [v. 0.5.0](https://github.com/Revertron/Alfis/releases/tag/v0.5.0).
