### ISSUE TITLE
The network thread often gets stuck

### ISSUE THREAD

**Issue by xaozai** [Revertron/Alfis#75]
The thread dealing with connections to other nodes periodically freezes, even when mining is not running. Thus, it is impossible to be sure that the mining will not be in vain, because the block will not be able to be up-to-date (match the previous one) and will not be able to be sent to the network.

**Comment by Revertron** [comment]
Do lines like `17:45:44 [INFO] alfis::p2p::network: Active nodes count: 17, banned count: 1, blocks count: 94` continue to appear in the log when you think that network is stuck?

**Comment by xaozai** [comment]
It seems that something has changed for the better in the latest versions. It hasn't stuck in the last 24 hours.
