### ISSUE TITLE
Can't connect Alfis 0.4.24

### ISSUE THREAD

**Issue by bitcoren** [Revertron/Alfis#77]
Can't connect
Alfis 0.4.24
Windows 10 Pro
Windows Server 2019
![изображение](https://user-images.githubusercontent.com/38252897/115798734-83555280-a409-11eb-8b94-f278933ed5fd.png)

**Comment by Revertron** [comment]
I see on my end: `Disconnecting socket for 3 spurious wakeups 204:22fd:9212:cb6c:cbed:1ca6:1877:898d`.
I seems that `mio:poll` is generating spurious wakeups: https://docs.rs/mio/0.7.11/mio/struct.Poll.html#spurious-events

Don't stop your node, I will try to debug it from my end, okay?

**Comment by bitcoren** [comment]
OK!

**Comment by Revertron** [comment]
> 
> 
> OK!

Aaaaand, your node is working normally right now, am I right?

**Comment by bitcoren** [comment]
Still not connecting
![изображение](https://user-images.githubusercontent.com/38252897/115799747-b1d42d00-a40b-11eb-9d7e-47a4a2ae9863.png)

**Comment by Revertron** [comment]
Did I correctly detect your address? Is it `204:22fd:9212:cb6c:cbed:1ca6:1877:898d`?

**Comment by bitcoren** [comment]
Yes.

**Comment by Revertron** [comment]
I see that my node is communicating with your without problem. Then, it must be an issue with GUI...
Can you try EDGE version?

**Comment by bitcoren** [comment]
I try both.

**Comment by bitcoren** [comment]
In my home PC, not EDGE is normal now.
![изображение](https://user-images.githubusercontent.com/38252897/115800576-7cc8da00-a40d-11eb-84b4-f427188cbeec.png)

**Comment by Revertron** [comment]
Maybe it is connected with some unusual security settings in IE and/or Edge?
Log shows that you have 20+ active nodes connected, and 104 blocks loaded. But it is not reflected in UI.

**Comment by bitcoren** [comment]
On my server not EDGE is OK now. Thanx.
![изображение](https://user-images.githubusercontent.com/38252897/115800960-34f68280-a40e-11eb-8a57-7d596601f2c5.png)

**Comment by Revertron** [comment]
Okay :)
