### ISSUE TITLE
Multiple keys in one instance

### ISSUE THREAD

**Issue by xaozai** [Revertron/Alfis#80]
I would like to be able to load multiple keys in a single ALFIS instance.

For example, I've mined three domains into three different keys. To be able to sign blocks, I have to run three instances with different keys, but this is redundant. Three instances are not needed for either nogui DNS or mining...

Thus, it would be good to run one nogui-instance on the server, which would work as DNS and sign blocks with three different keys.

**Comment by Revertron** [comment]
Yes, I have this in plan.

**Comment by xaozai** [comment]
Implemented in v. 0.5.5
